# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5cba98533ef245eec580aa3381a2300ab18e4f17b07b8b4d8f4dbbe3b28a67e9044d47c39f7389ed99d41598dd71a33276ade589c9d334d002db3c55b674109d

test:
  secret_key_base: 12e64addc44e4ff808c1d7e61187bf0d12ff6caf9dc2e7b965732c48cc2a6ef6bd96db273efff7fd273bb135bbd8e9a3e4269ff3d4d5fb1f8696c3a30a59bb55

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
